### ISSUE TITLE
Failed Filter

### ISSUE THREAD

**Issue by hartwct27** [LazZiya/PagingSampleProject#1]
Error after click search, Query string doesn't exists (just https://localhost:44351/Example/Error?).
Backend:
   [BindProperty(SupportsGet = true)]
   public string Q { get; set; } = string.Empty;
     public async Task OnGet()
        {
           if (!string.IsNullOrEmpty(Q))
            {
               //linq where
            }
       }

     Html Page Tag:
    <form method="get" class="form-inline">
        <input asp-for="Q" class="form-control" />
        <button type="submit" class="btn btn-primary">Search</button> 
    </form>
    
        <paging page-no="Model.P"
                page-size="Model.S"
                total-records="Model.TotalRecords"
                query-string-value="@(Request.QueryString.Value)">
        </paging>

**Comment by hartwct27** [comment]
![image](https://user-images.githubusercontent.com/18733334/108213247-62e6ee80-7161-11eb-8d3e-b56cf936f9eb.png)

The Error after click search @LazZiya

**Comment by LazZiya** [comment]
Hi @hartwct27 

Which version you are using? `query-string-value` is deprecated and you don't have to use it in the current version.

See all attributes in the [docs](https://docs.ziyad.info/en/LazZiya.TagHelpers/v5.0/Paging-TagHelper-Attributes.md)

**Comment by LazZiya** [comment]
I've updated the sample project in this repository, you may give it a try.

**Comment by hartwct27** [comment]
Thanks @LazZiya for your response.
My Solving is:

    <form method="get" class="form-inline">
        <input name="Q" value="@Model.Q" class="form-control" />
        <button type="submit" class="btn btn-primary">Search</button>
    </form>
    
    Paging Tags:
    
     <paging page-no="Model.P"
                page-size="Model.S"
                total-records="Model.TotalRecords">
        </paging>

Then string Q will be used for list filter in backend.
